apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ops
  name: devbind
subjects:
- kind: User
  name: dev
  apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: Role
  name: service-reader
  apiGroup: "rbac.authorization.k8s.io"
